### ISSUE TITLE
Pump panic with uptime tests

### ISSUE THREAD

**Issue by maciejwojciechowski** [TykTechnologies/tyk-pump#207]
branch: master

When you enable Uptime Tests for API the pump crashes with panic

```
panic: interface conversion: interface {} is string, not []uint8

goroutine 1 [running]:
github.com/TykTechnologies/tyk-pump/pumps.(*MongoPump).WriteUptimeData(0x2614660, 0xc0001fd110, 0x1, 0x1)
	/Users/tyk/work/src/github.com/TykTechnologies/tyk-pump/pumps/mongo.go:397 +0xfb0
main.StartPurgeLoop(0x5)
	/Users/tyk/work/src/github.com/TykTechnologies/tyk-pump/main.go:194 +0x1fd
main.main()
	/Users/tyk/work/src/github.com/TykTechnologies/tyk-pump/main.go:246 +0x40e
```

This works fine on v0.8.3 tag

pump.conf

```
{
        "analytics_storage_type": "redis",
    "analytics_storage_config": {
        "type": "redis",
        "host": "localhost",
        "port": 6379,
        "redis_use_ssl": false,
        "redis_ssl_insecure_skip_verify": true,
        "addrs": [],
        "master_name": "",
        "username": "",
        "password": "",
        "database": 0,
        "optimisation_max_idle": 100,
        "optimisation_max_active": 0,
        "enable_cluster": false
    },
    "purge_delay": 5,
    "pumps": {
        "mongo": {
            "name": "mongo",
            "meta": {
                "collection_name": "tyk_analytics",
                "mongo_url": "mongodb://tyk-mongo:27017/tyk_analytics",
                "collection_cap_enable": true
            }
        },
        "mongo-pump-aggregate": {
            "name": "mongo-pump-aggregate",
            "meta": {
                "mongo_url": "mongodb://tyk-mongo:27017/tyk_analytics",
                "use_mixed_collection": true,
                "collection_cap_enable": true
            }
        },
        "mongo-pump-selective": {
            "name": "mongo-pump-selective",
            "meta": {
                "mongo_url": "mongodb://tyk-mongo:27017/tyk_analytics",
                "use_mixed_collection": true,
                "collection_cap_enable": true
            }
        }
    },
    "uptime_pump_config": {
        "collection_name": "tyk_uptime_analytics",
        "mongo_url": "mongodb://tyk-mongo:27017/tyk_analytics"
    },
    "dont_purge_uptime_data": false
}
```

**Comment by maciejwojciechowski** [comment]
verified
